releases:

- name:    "routing"
  version: "0.275.0"
  url:     "https://bosh.io/d/github.com/cloudfoundry/routing-release?v=0.275.0"
  sha1:    "6dd63d1653bf333ea64fca061a3a16d9be2e750f"

- name:    "bpm"
  version: "1.2.1"
  sha1:    "36299a55c00d28cfe54bbb4772ca617f52d76adb"
  url:     "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.2.1"

- name:    "bosh-dns-aliases"
  version: "0.0.4"
  sha1:    "55b3dced813ff9ed92a05cda02156e4b5604b273"
  url:     "https://bosh.io/d/github.com/cloudfoundry/bosh-dns-aliases-release?v=0.0.4"
