---
params:
  pg_username: (( vault meta.vault "/db:username" ))
  pg_password: (( vault meta.vault "/db:password" ))

instance_groups:
- name: scheduler
  jobs:
  - (( delete "postgres" ))

---
- type: remove
  path: /instance_groups/0/jobs/name=scheduler/consumes

