---
meta:
  pg:
    scheme:   (( vault meta.vault "/db:scheme"   ))
    username: (( vault meta.vault "/db:username" ))
    password: (( vault meta.vault "/db:password" ))
    hostname: (( vault meta.vault "/db:hostname" ))
    port:     (( vault meta.vault "/db:port"     ))
    sslmode:  (( vault meta.vault "/db:sslmode"  ))
    database: (( vault meta.vault "/db:database" ))

instance_groups:
- name: scheduler
  jobs:
  - (( delete "postgres" ))

