---
params:
  pg_scheme:   (( grab params.db.scheme   || meta.db.scheme   )) 
  pg_username: (( grab params.db.username || meta.db.username )) 
  pg_password: (( grab params.db.password || meta.db.password )) 
  pg_hostname: (( grab params.db.hostname || meta.db.hostname )) 
  pg_port:     (( grab params.db.port     || meta.db.port     )) 
  pg_database: (( grab params.db.database || meta.db.database )) 
  pg_sslmode:  (( grab params.db.sslmode  || meta.db.sslmode  )) 

instance_groups:
- name: scheduler
  jobs:
  - (( delete "postgres" ))

---
- type: remove
  path: /instance_groups/0/jobs/name=scheduler/consumes

