---
meta:
  db:
    scheme:   (( vault meta.vault "/db/scheme" ))
    username: (( vault meta.vault "/db/username" ))
    password: (( vault meta.vault "/db/password" ))
    hostname: (( vault meta.vault "/db/hostname" ))
    port:     (( vault meta.vault "/db/port" ))
    database: (( vault meta.vault "/db/database" ))
    sslmode:  "verify-ca"

params:
  pg_scheme:   (( grab meta.db.scheme   ))
  pg_username: (( grab meta.db.username ))
  pg_password: (( grab meta.db.password ))
  pg_hostname: (( grab meta.db.hostname ))
  pg_port:     (( grab meta.db.port     ))
  pg_sslmode:  (( grab meta.db.sslmode  ))
  pg_database: (( grab meta.db.database ))

instance_groups:
- name: scheduler
  jobs:
  - (( delete "postgres" ))

---
- type: remove
  path: /instance_groups/0/jobs/name=scheduler/consumes

