---
params:
  pg:
    host:   (( param "Please provide the hostname / IP of your external PostgreSQL database instance." ))
    port:   5432
    scheme: postgres
    user:   (( vault.path "external_db:username"))
    pass:   (( vault.path "external_db:password"))

    #sslmode: enable

instance_groups:
- name: scheduler
  jobs:
  - (( delete "postgres" ))
