---
meta:
  default_bosh_exodus_path:     (( concat $GENESIS_ENVIRONMENT "/bosh" ))
  bosh_exodus_path:             (( grab params.bosh_exodus_path || meta.default_bosh_exodus_path ))

  default:
    azs: [z1]
  pg:
    host: "127.0.0.1"
    port: "5432"
    user: "scheduler-admin"
    pass: (( vault meta.vault "/role:password" ))
  cf:
    exodus: (( concat $GENESIS_EXODUS_MOUNT params.cf.deployment_env "/" params.cf.deployment_type ))
    deployment_name: (( concat params.cf.deployment_env "-" params.cf.deployment_type ))
    system_domain: (( vault "secret/exodus/" meta.bosh_exodus_path "/cf:system_domain" ))

params:
  cf:
    deployment_env:  (( grab genesis.env )) # assume the same env name as cf env
    deployment_type: cf # for crazy people using an non-"cf" cf deployment name
    core_network:    (( vault meta.cf.exodus ":core_network" ))
    system_domain:   (( vault meta.cf.exodus ":system_domain" ))
    system_org:      (( vault meta.cf.exodus ":system_org" ))
    system_space:    (( vault meta.cf.exodus ":system_space" ))
    username:        (( vault meta.cf.exodus ":admin_username" ))
    password:        (( vault meta.cf.exodus ":admin_password" ))
  network:           (( grab params.cf.core_network ))
  nats:
    client_cert: (( vault meta.cf.exodus ":nats_client_cert" ))
    client_key:  (( vault meta.cf.exodus ":nats_client_key" ))
  uaa:
    client_id:     (( vault meta.cf.exodus ":app_scheduler_client" ))
    client_secret: (( vault meta.cf.exodus ":app_scheduler_secret" ))
  scheduler:
    domain:  (( concat "scheduler." meta.cf.system_domain ))
  pg:
    sslmode: "disable"
    database: "scheduler"

instance_groups:
- name:      scheduler
  instances: 1
  azs:      (( grab params.availability_zones || meta.default.azs ))
  stemcell: default
  networks: 
  - name:  (( grab params.network || "default" ))
  vm_type: (( grab params.vm_type || "default" ))

  jobs: 
  - name: scheduler
    release: scheduler-boshrelease
    consumes:
      postgres:
        from: scheduler-postgres

    properties:
      scheduler:
        uaa:
          client_id: (( grab params.uaa.client_id ))
          client_secret: (( grab params.uaa.client_secret ))
          endpoint: (( concat "https://uaa."  params.cf.system_domain ))
        cf:
          api: (( concat "https://api." params.cf.system_domain ))
        postgres:
          uri: (( concat "postgres://" params.pg.user ":" params.pg.pass "@" params.pg.host ":" params.pg.port "/" params.pg.database "?sslmode=" params.pg.sslmode ))

  - name: postgres
    properties:
      databases:
        roles:
          - name:     (( grab params.pg.user))
            password: (( grab params.pg.pass))
        databases: 
        - name: (( grab params.pg.database ))
        port:   (( grab params.pg.port ))
    provides:
      postgres:
        as: scheduler-postgres
    release: postgres

- name: smoke-tests
  instances: 1
  azs:       (( grab params.availability_zones || meta.default.azs ))
  stemcell:  default
  networks:  
  - name:    (( grab params.network || "default" ))
  vm_type:   (( grab params.vm_type || "default" ))
  lifecycle: errand

  jobs:
  - name: smoke-tests
    release: scheduler-boshrelease
    properties:
      cf:
        username:     (( grab params.cf.username ))
        password:     (( grab params.cf.password ))
        api:          (( concat "https://api." params.cf.system_domain ))
        organization: (( grab params.cf.system_org ))
        space:        (( grab params.cf.system_space ))

update:
  serial:            false
  canaries:          1
  max_in_flight:     1
  max_errors:        1
  canary_watch_time: 5000-600000
  update_watch_time: 5000-600000

stemcells:
  - alias:   default
    os:      (( grab params.stemcell_os      || "ubuntu-bionic" ))
    version: (( grab params.stemcell_version || "latest" ))

name: scheduler

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000

